plugins {
    id "com.android.application"
}

android {
    namespace "com.opencacnlabs.dalmaadventure"
    compileSdk 35

    defaultConfig {
        applicationId "com.opencacnlabs.dalmaadventure.test"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "0.1.2-test"
    }
}
